eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

server:
  port: 8070

spring:
  application:
    name: schools
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://localhost:1433;databaseName=schools
    username: username
    password: password
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true # Opcional, para mostrar as consultas SQL no console
    database-platform: org.hibernate.dialect.SQLServerDialect

application:
  config:
    students-url: http://localhost:8222/api/v1/students

management:
  tracing:
    sampling:
      probability: 1.0
