server:
  port: 8090
spring:
  application:
    name: students
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://localhost:1433;databaseName=schools
    username: username
    password: password
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true # Isso é opcional, para mostrar as consultas SQL no console
    database-platform: org.hibernate.dialect.SQLServerDialect

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

management:
  tracing:
    sampling:
      probability: 1.0
