version: '3'
services:
  sqlserver:
    container_name: sqlserver
    image: mcr.microsoft.com/mssql/server
    environment:
      SA_PASSWORD: Strong_Password123
      ACCEPT_EULA: Y
    ports:
      - "1433:1433"
    networks:
      - sqlserver
    restart: unless-stopped

  zipkin:
    container_name: zipkin
    image: openzipkin/zipkin
    ports:
      - "9411:9411"
    networks:
      - zipkin

networks:
  sqlserver:
    driver: bridge
  zipkin:
    driver: bridge
